name: Continuous Integration

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Build
        run: mvn build -B

      - name: Maven Clean Install
        run: mvn clean install -B

      - name: Maven Test
        run: mvn test -B

      - name: Maven Run (Background) and Wait
        run: |
          mvn spring-boot:run &
          sleep 15 # Adjust sleep time as needed for your application to start

      - name: Check if App is Running (Optional)
        run: |
          curl http://localhost:8080 # Assuming your app runs on port 8080
          if [ $? -eq 0 ]; then
            echo "Application is running successfully!"
          else
            echo "Failed to connect to the application."
            exit 1
          fi